spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://150.158.85.107:6001/industrial_park?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: gkdz
      password: GKDZ@mysql$gkdz#qwe123.
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 2
    host: 150.158.85.107
    port: 6002
    password: gkdz&redis$admin#pwd.r1    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

my:
  #默认接口字段配置
  minio:
    url: http://150.158.85.107:6003/
    accessKey: gkdz
    secretKey: GKDZ@minio@admin@123456.
    bucketName: park
    redisKeypre: minio
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    #    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

knife4j:
  enable: true
  token: defaultToken
pagehelper:
  helper-dialect: mysql

xxl:
  job:
    admin:
      addresses: http://150.158.85.107:30001/xxl-job-admin
    accessToken: gkdz&xxljob$linux#123_08.
    executor:
      appname: IndustrialPark
      address:
      ip:
      port: 10021
      logpath: './log'
      logretentiondays: 30


config:
  freesdk:
    app-id: EEUFHK7EQ7RWXJkApa5kjxjJ1t7DQZezURVbUQmy2i6
    sdk-key: 4QCCCvPFrx9VVXxwpGYLu8KGLtyrBWGfZDz7xCW295DT
    thread-pool-size: 5